title:    Chamal Gomes

logo: test_image_1.png # Use a relative path to logo image 

description: Advanced Analytics and AI in Healthcare

show_downloads: true

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-ta
